name       : dav1d
version    : 0.2.0
release    : 1
source     :
    - https://code.videolan.org/videolan/dav1d/-/archive/0.2.0/dav1d-0.2.0.tar.bz2 : b7d0db946e112f46140043360a0d7dacd5b3087cc888fffcb4d2eb90e85a0d60
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : AV1 decoder targeted to be small and fast
description: |
    dav1d is a new AV1 cross-platform Decoder, open-source, and focused on speed and correctness.
setup      : |
    %meson_configure --buildtype=release
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
