name       : dav1d
version    : 0.8.2
release    : 14
source     :
    - https://code.videolan.org/videolan/dav1d/-/archive/0.8.2/dav1d-0.8.2.tar.bz2 : 78ec7a1714d98a8f4ecbc4255e83e6c4c944cdd881871ea234ce40153fd3df04
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : AV1 decoder targeted to be small and fast
description: |
    dav1d is a new AV1 cross-platform Decoder, open-source, and focused on speed and correctness.
setup      : |
    %meson_configure --buildtype=release
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
