name       : dav1d
version    : 0.3.0
release    : 4
source     :
    - https://code.videolan.org/videolan/dav1d/-/archive/0.3.0/dav1d-0.3.0.tar.bz2 : 22946ddd8c5122d3490b250933328c3278da21b0659db9b7fa8f875e4735c2e6
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : AV1 decoder targeted to be small and fast
description: |
    dav1d is a new AV1 cross-platform Decoder, open-source, and focused on speed and correctness.
setup      : |
    %meson_configure --buildtype=release
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
