name       : dav1d
version    : 1.0.0
release    : 20
source     :
    - https://code.videolan.org/videolan/dav1d/-/archive/1.0.0/dav1d-1.0.0.tar.bz2 : 4a4eb6cecbc8c26916ef58886d478243de8bcc46710b369c04d6891b0155ac0f
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : AV1 decoder targeted to be small and fast
description: |
    dav1d is a new AV1 cross-platform Decoder, open-source, and focused on speed and correctness.
builddeps  :
    - pkgconfig(libxxhash)
setup      : |
    %meson_configure --buildtype=release
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
