name       : dav1d
version    : 0.9.1
release    : 17
source     :
    - https://code.videolan.org/videolan/dav1d/-/archive/0.9.1/dav1d-0.9.1.tar.bz2 : fb2a050e6c2410c99104f631e202a02697dfe1a2fc9acc3c50a16422aefb004c
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : AV1 decoder targeted to be small and fast
description: |
    dav1d is a new AV1 cross-platform Decoder, open-source, and focused on speed and correctness.
builddeps  :
    - pkgconfig(libxxhash)
setup      : |
    %meson_configure --buildtype=release
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
