name       : dav1d
version    : 1.2.1
release    : 23
source     :
    - https://code.videolan.org/videolan/dav1d/-/archive/1.2.1/dav1d-1.2.1.tar.bz2 : a4003623cdc0109dec3aac8435520aa3fb12c4d69454fa227f2658cdb6dab5fa
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : AV1 decoder targeted to be small and fast
description: |
    dav1d is a new AV1 cross-platform Decoder, open-source, and focused on speed and correctness.
builddeps  :
    - pkgconfig(libxxhash)
setup      : |
    %meson_configure --buildtype=release
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
